### ISSUE TITLE
Problem with executing configurator

### ISSUE THREAD

**Issue by dmiego** [tango-controls-hdbpp/hdbpp-configurator#4]
Hello.

I've downloaded the source code from this repo, compiled it with maven and tried to launch hdbpp-configurator, but it hasn't found its' main class 
```
./start_gui.sh -configure
CLASSPATH=/usr/local/share/java/JTango.jar:/usr/local/share/java/ATKCore.jar:/usr/local/share/java/ATKWidget.jar:/home/tango/wk/hdbpp-configurator/target/hdbpp-configurator.jar:/usr/local/share/java/Jive.jar
Error: Could not find or load main class org.tango.hdb_configurator.configurator.HdbConfigurator
```
I edited start-gui to match my system configuration (Debian 9.7), here it is:
```
#!/bin/bash
# Define the class path
#
TANGO_JAVA_LIBS=/usr/local/share/java
APP_DIR=/home/tango/wk/hdbpp-configurator/target

JTANGO=$TANGO_JAVA_LIBS/JTango.jar
ATK=$TANGO_JAVA_LIBS/ATKCore.jar:$TANGO_JAVA_LIBS/ATKWidget.jar
CONFIGURATOR=$APP_DIR/hdbpp-configurator.jar
JIVE=$TANGO_JAVA_LIBS/Jive.jar

CLASSPATH=$JTANGO:$ATK:$CONFIGURATOR:$JIVE
echo "CLASSPATH=$CLASSPATH"

#
# Define the default GUI
#
APPLI_JAR=$APP_DIR/hdbpp-configurator.jar
APPLI_PACKAGE=org.tango.hdb_configurator
APPLI_MAIN_CLASS=configurator.HdbConfigurator

#
# Gives the hdbpp-cm-srv device
#
export HdbManager=sys/tools/hdb++cm

#=====================================
#
#            Main part
#
#=====================================
DisplaySyntax() {
        echo ""
        echo "$0: "
        echo "Options:"
        echo "   -configure: Start HDB++ configurator"
        echo "   -diag:      Start HDB++ diagnostics window"
        echo "   -servers:   Start HDB++ server status window"
        echo "   --help:     Display this message"
}
#=====================================


case "$1" in
# ----------------------------------------------
    -configure)
        # Start Configurator
        /usr/bin/java $APPLI_PACKAGE.$APPLI_MAIN_CLASS
    ;;
    
# ----------------------------------------------
    -diag)
        # Display disgnostics
        java  $APPLI_PACKAGE.diagnostics.HdbDiagnostics
    ;;
    
# ----------------------------------------------
    -servers)
        # Display servers status
        java  $APPLI_PACKAGE.diagnostics.ServerInfoTable
    ;;
    
# ----------------------------------------------
    *)
        # Default case  --> Display Syntax
        DisplaySyntax
    ;;
esac

```

When I tried to execute .jar without any dependencies, I've got message:
```
java -cp hdbpp-configurator-3.11-SNAPSHOT.jar org.tango.hdb_configurator.configurator.HdbConfigurator
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: fr/esrf/Tango/DevFailed
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: fr.esrf.Tango.DevFailed
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
```

Also I downloaded compiled .jars from bintray and got the same errors.

What am i doing wrong and can you help me to solve this problem?

**Comment by Pascal-Verdier** [comment]
Hi Diego
When you try with:
`
java -cp hdbpp-configurator-3.11-SNAPSHOT.jar org.tango.hdb_configurator.configurator.HdbConfigurator
`
Wou have:
`
java.lang.NoClassDefFoundError: fr/esrf/Tango/DevFailed
`
It is normal. The class fr/esrf/Tango/DevFailed come from JTango.jar witch is not in your $CLASSPATH

You need all jar files specified in the script.
I think, in your directory **/home/tango/wk/hdbpp-configurator/target** you do not have  a 
**hdbpp-configurator.jar** but a file named **hdbpp-configurator-3.11-SNAPSHOT.jar**

use:
 * mv hdbpp-configurator-3.11-SNAPSHOT.jar hdbpp-configurator.jar 
or
 * ln -s hdbpp-configurator-3.11-SNAPSHOT.jar hdbpp-configurator.jar
or
 * change the jar file name in the script.

It should solve your problem.
Regards
Pascal

**Comment by dmiego** [comment]
Actually I have it, I've made softlink to 3.11-SNAPSHOT file, just forgot to mention it.
So it's not the solution to the problem.

**Comment by Pascal-Verdier** [comment]
The script given as example is not dependent of your jar release.
So you need to change your jar name or adapt you script

**Comment by Pascal-Verdier** [comment]
If it is not the solution to the problem, what is the stack trace now ?

**Comment by dmiego** [comment]
Quote from ls -la:
```
-rw-r--r-- 1 tango tango 698343 Jan 30 11:43 hdbpp-configurator-3.11-SNAPSHOT.jar
lrwxrwxrwx 1 tango tango     36 Jan 31 11:30 hdbpp-configurator.jar -> hdbpp-configurator-3.11-SNAPSHOT.jar
```

I still have the same error:
`Error: Could not find or load main class org.tango.hdb_configurator.configurator.HdbConfigurator`

**Comment by Pascal-Verdier** [comment]
You confirm that the jar file and it link are in path:
/home/tango/wk/hdbpp-configurator/target/

**Comment by dmiego** [comment]
```
tango@mpd-tof-sc-1:~/wk/hdbpp-configurator/target$ pwd
/home/tango/wk/hdbpp-configurator/target
tango@mpd-tof-sc-1:~/wk/hdbpp-configurator/target$ ls -la
total 1400
drwxr-xr-x 6 tango tango   4096 Jan 31 11:39 .
drwxr-xr-x 7 tango tango   4096 Jan 30 16:13 ..
drwxr-xr-x 3 tango tango   4096 Jan 30 11:40 classes
drwxr-xr-x 3 tango tango   4096 Jan 30 11:40 generated-sources
-rw-r--r-- 1 tango tango 698365 Jan 30 16:19 hdbpp-configurator-3.10.jar
-rw-r--r-- 1 tango tango 698343 Jan 30 11:43 hdbpp-configurator-3.11-SNAPSHOT.jar
lrwxrwxrwx 1 tango tango     77 Jan 31 11:39 hdbpp-configurator.jar -> /home/tango/wk/hdbpp-configurator/target/hdbpp-configurator-3.11-SNAPSHOT.jar
drwxr-xr-x 2 tango tango   4096 Jan 30 11:43 maven-archiver
drwxr-xr-x 3 tango tango   4096 Jan 30 11:40 maven-status
-rwxr-xr-x 1 tango tango   1805 Jan 30 16:59 start_gui.sh
```

**Comment by Pascal-Verdier** [comment]
It think you should have:
hdbpp-configurator.jar -> hdbpp-configurator-3.11-SNAPSHOT.jar
and not
hdbpp-configurator.jar -> /home/tango/wk/hdbpp-configurator/target/hdbpp-configurator-3.11-SNAPSHOT.jar

**Comment by dmiego** [comment]
If you look on my previous message, you'll see this version. I've just changed it to check if it helps.
Still no effect.

**Comment by Pascal-Verdier** [comment]
And if you change the jar file name in the script (for 3.10 and 3.11-SNAPSHOT) ?
Because here we use link as specified above and it works.

**Comment by dmiego** [comment]
No change.
Tried to do the same steps on a different VM with Debian 8.8 - the same situation.
And I have no idea what is the cause of the problem. 

Well, thanks for help. I think we'll continue to use jhdbcpp for now.

**Comment by dmiego** [comment]
Hello.
I've downloaded TangoBox image and copied script and .jar files to my VM and configurator finally launched.
TangoBox has only 2.2 version of configurator, so I replaced it with 3.10 from bintray, and it's also OK.

I think the problem was with arguments for java, maybe it's different for Ubuntu and Debian?

```
#!/bin/bash

TANGO_HOME=/usr/local/share/java
TANGO_LIBS=$TANGO_HOME
TANGO_APP=$TANGO_HOME

Appli=$TANGO_APP/hdbpp-configurator-3.10.jar

CLASSPATH=$TANGO_LIBS/JTango.jar:$TANGO_LIBS/ATKWidget.jar:$TANGO_LIBS/ATKCore.jar
CLASSPATH=$CLASSPATH:$TANGO_APP/Jive.jar:$Appli
export CLASSPATH
echo CLASSPATH $CLASSPATH

export TANGO_HOST=mpd-tof-sc-1.he.jinr.ru:10000
export HdbManager=sys/tools/hdb++cm
export JNIPATH=-Djava.library.path=/usr/lib/x86_64-linux-gnu/

if [ "$#" -lt 1 ]
then
    java   $JNIPATH -cp $CLASSPATH org.tango.hdb_configurator.configurator.HdbConfigurator
else
    if [ $1 = "-diag" ]
    then 
        java  $JNIPATH -cp $CLASSPATH org.tango.hdb_configurator.diagnostics.HdbDiagnostics
    else
        java  $JNIPATH -cp $CLASSPATH org.tango.hdb_configurator.configurator.HdbConfigurator
    fi
fi
```
